export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_REVISIONS = 'TOGGLE_REVISIONS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
