export const FETCH_REQUIREMENTS = 'FETCH_REQUIREMENTS';
export const RECEIVE_REQUIREMENTS = 'RECEIVE_REQUIREMENTS';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_REVISIONS = 'TOGGLE_REVISIONS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
