export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_CATEGORY_TYPE = 'SELECT_CATEGORY_TYPE';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const UPDATE_INPUT = 'UPDATE_INPUT';

export const ADD_DROPDOWN = 'ADD_DROPDOWN';
export const RESET_DROPDOWNS = 'RESET_DROPDOWNS';
export const SET_INITIAL_CATEGORY_SELECTOR_STATE = 'SET_INITIAL_CATEGORY_SELECTOR_STATE';