export const FETCH_REQUIREMENTS = 'FETCH_REQUIREMENTS';
export const RECEIVE_REQUIREMENTS = 'RECEIVE_REQUIREMENTS';
export const DOCUMENTS_RECEIVING = 'DOCUMENTS_RECEIVING';

export const DOCUMENT_REMOVING = 'DOCUMENT_REMOVING';
export const DOCUMENT_UPLOAD_IN_PROGRESS = 'DOCUMENT_UPLOAD_IN_PROGRESS';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED';

export const IN_PROGRESS = 'IN_PROGRESS';
export const FAILED = 'FAILED';
export const SUCCESS = 'SUCCESS';

export const FETCH_FAILED = 'FETCH_FAILED';