# PlantMiner Components
image:
  name: plantminer/ci:v1.5
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL
pipelines:
  branches:
    master:
      - step:
          caches:
            - npm
          script:
            # Build boilerplate
            - cd boilerplate && npm install && cd -
            - cd boilerplate && npm run build && cd -

            # Build category-selector
            - cd category-selector && npm install && cd -
            - cd category-selector && npm run build && cd -

definitions:
  caches:
    npm: ~/.npm
