export const UPDATE_QUOTE_ID = 'UPDATE_QUOTE_ID';

export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_ERROR = 'LOAD_ITEMS_ERROR';

export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const UPDATE_SUGGESTION = 'UPDATE_SUGGESTION';

export const LOAD_ITEM_DETAILS_SUCCESS = 'LOAD_ITEM_DETAILS_SUCCESS';
export const LOAD_ITEM_DETAILS_ERROR = 'LOAD_ITEM_DETAILS_ERROR';
export const RESET_ITEM_DETAILS = 'RESET_ITEM_DETAILS';
export const PRICING_OPTIONS_RECEIVED = 'PRICING_OPTIONS_RECEIVED';
export const RECEIVE_NEW_ENGAGEMENT = 'RECEIVE_NEW_ENGAGEMENT';

export const UPDATE_TEXT = 'UPDATE_TEXT';
export const UPDATE_PRICING_OPTION = 'UPDATE_PRICING_OPTION';
export const UPDATE_PURCHASE_ORDER = 'UPDATE_PURCHASE_ORDER';
export const UPDATE_PLAN_DATE = 'UPDATE_PLAN_DATE';
export const UPDATED_ENGAGEMENT = 'UPDATED_ENGAGEMENT';

export const RECEIVE_ENGAGEMENTS = 'RECEIVE_ENGAGEMENTS';
export const ENGAGEMENT_DELETED = 'ENGAGEMENT_DELETED';
export const UPDATED_ENGAGEMENT_DETAILS = 'UPDATED_ENGAGEMENT_DETAILS';
export const UPDATED_UNIT = 'UPDATED_UNIT';
