export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const DISPLAY_SUCCESS = 'DISPLAY_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS';

export const COMPONENT_SPOT = 'COMPONENT_SPOT';
export const UPDATE_QUOTE_ID = 'UPDATE_QUOTE_ID';
export const UPDATE_REQUESTED_ITEM_ID = 'UPDATE_REQUESTED_ITEM_ID';
export const UPDATE_MATCHED_ITEM_ID = 'UPDATE_MATCHED_ITEM_ID';
export const UPDATE_PANEL_ID = 'UPDATE_PANEL_ID';
export const UPDATE_REGION_ID = 'UPDATE_REGION_ID';
export const UPDATE_ITEM_ID = 'UPDATE_ITEM_ID';


export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_ERROR = 'LOAD_ITEMS_ERROR';

export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const UPDATE_SUGGESTION = 'UPDATE_SUGGESTION';

export const RESET_ITEM_DETAILS = 'RESET_ITEM_DETAILS';
export const PRICING_OPTIONS_RECEIVED = 'PRICING_OPTIONS_RECEIVED';
export const RECEIVE_NEW_ENGAGEMENT = 'RECEIVE_NEW_ENGAGEMENT';

export const UPDATE_TEXT = 'UPDATE_TEXT';
export const UPDATE_PRICING_OPTION = 'UPDATE_PRICING_OPTION';
export const RESET_PRICING_OPTIONS = 'RESET_PRICING_OPTIONS';
export const UPDATE_PURCHASE_ORDER = 'UPDATE_PURCHASE_ORDER';
export const UPDATE_PLAN_DATE = 'UPDATE_PLAN_DATE';
export const UPDATED_ENGAGEMENT = 'UPDATED_ENGAGEMENT';
export const UPDATE_NOTIFY_ALL = 'UPDATE_NOTIFY_ALL';

export const RECEIVE_ENGAGEMENTS = 'RECEIVE_ENGAGEMENTS';
export const RESET_CURRENT_ENGAGEMENT = 'RESET_CURRENT_ENGAGEMENT';
export const ENGAGEMENT_DELETED = 'ENGAGEMENT_DELETED';
export const UPDATED_ENGAGEMENT_DETAILS = 'UPDATED_ENGAGEMENT_DETAILS';
export const UPDATED_UNIT = 'UPDATED_UNIT';
