export const FETCH_REVISIONS = 'FETCH_REVISIONS';
export const RECEIVE_REVISIONS = 'RECEIVE_REVISIONS';

export const DOWNLOAD_REVISION = 'DOWNLOAD_REVISION';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const REQUEST_FAILED = 'REQUEST_FAILED';
