export const FETCH_SECTIONS = 'FETCH_SECTIONS';
export const RECEIVE_SECTIONS = 'RECEIVE_SECTIONS';

export const TOGGLE_SECTION = 'TOGGLE_SECTION';
export const SWITCH_TAB = 'SWITCH_TAB';

export const TOGGLE_STATUS = 'TOGGLE_STATUS';

export const TOGGLE_COMMENT_BOX = 'TOGGLE_COMMENT_BOX';
export const TOGGLE_COMMENT_EDIT = 'TOGGLE_COMMENT_EDIT';
export const SUBMITTED_COMMENT =  'SUBMITTED_COMMENT';
export const SUBMITTING_COMMENT = 'SUBMITTING_COMMENT';