export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';

export const UPDATED_CHECKBOX_VALUE = 'UPDATED_CHECKBOX_VALUE';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const ADD_NEW_DOCUMENT = 'ADD_NEW_DOCUMENT';

export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const SELECT_SUGGESTION = 'SELECT_SUGGESTION';