export const REQUIREMENTS_REQUESTED = 'REQUIREMENTS_REQUESTED';
export const REQUIREMENTS_RECEIVED = 'REQUIREMENTS_RECEIVED';

export const COMMENT_IS_SAVED = 'COMMENT_IS_SAVED';
export const COMMENTS_FIELD_IS_DISPLAYED = 'COMMENTS_FIELD_IS_DISPLAYED';

export const SELECTION_IS_SAVED = 'SELECTION_IS_SAVED';
export const SELECTION_UPDATE_REQUESTED = 'SELECTION_UPDATE_REQUESTED';
