export const REQUIREMENTS_REQUESTED = 'REQUIREMENTS_REQUESTED';
export const REQUIREMENTS_RECEIVED = 'REQUIREMENTS_RECEIVED';
export const UPDATE_QUOTE_ID = 'UPDATE_QUOTE_ID';
export const UPDATE_QUOTE_ITEM_ID = 'UPDATE_QUOTE_ITEM_ID';

export const ADD_DEFAULT_SUPPLIER_RESPONSE = 'ADD_DEFAULT_SUPPLIER_RESPONSE';
export const UPDATE_SUPPLIER_RESPONSE_ID = 'UPDATE_SUPPLIER_RESPONSE_ID';

export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const TOGGLE_COMMENTS_DISPLAY = 'TOGGLE_COMMENTS_DISPLAY';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const SAVE_COMMENTS = 'SAVE_COMMENTS';