export const REQUIREMENTS_REQUESTED = 'REQUIREMENTS_REQUESTED';
export const REQUIREMENTS_RECEIVED = 'REQUIREMENTS_RECEIVED';

export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const TOGGLE_COMMENTS_DISPLAY = 'TOGGLE_COMMENTS_DISPLAY';
