export const DOCUMENTS_RECEIVING = 'DOCUMENTS_RECEIVING';
export const DOCUMENTS_FETCHING = 'DOCUMENTS_FETCHING';

export const GROUP_TOGGLE = 'GROUP_TOGGLE';

export const DOCUMENT_TOGGLE = 'DOCUMENT_TOGGLE';

export const REQUESTED_ITEMS_FETCHING = 'REQUESTED_ITEMS_FETCHING';
export const REQUESTED_ITEMS_RECEIVING = 'REQUESTED_ITEMS_RECEIVING';
export const REQUESTED_ITEM_TOGGLE = 'REQUESTED_ITEM_TOGGLE';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';