export const DOCUMENTS_RECEIVING = 'DOCUMENTS_RECEIVING';
export const DOCUMENTS_FETCHING = 'DOCUMENTS_FETCHING';
export const DOCUMENTS_SELECT_ALL = 'DOCUMENTS_SELECT_ALL';

export const REQUESTED_ITEMS_FETCHING = 'REQUESTED_ITEMS_FETCHING';
export const REQUESTED_ITEMS_RECEIVING = 'REQUESTED_ITEMS_RECEIVING';
export const REQUESTED_ITEM_TOGGLE = 'REQUESTED_ITEM_TOGGLE';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';