export const FETCH_STAFF = 'FETCH_STAFF';
export const RECEIVE_STAFF = 'RECEIVE_STAFF';

export const FETCH_PREFERRED_SUPPLIERS = 'FETCH_PREFERRED_SUPPLIERS';
export const RECEIVE_PREFERRED_SUPPLIERS = 'RECEIVE_PREFERRED_SUPPLIERS';
export const DOWNLOADED_PREFERRED_SUPPLIERS = 'DOWNLOADED_PREFERRED_SUPPLIERS';

export const CHANGE_STATUS_FILTER = '';
export const TOGGLE_COMMENT_MODAL = 'TOGGLE_COMMENT_MODAL';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT';

export const TOGGLE_SUPPLIER_ROW = 'TOGGLE_SUPPLIER_ROW';

export const API_ERROR = 'API_ERROR';
