export const RECEIVING_GROUPS = 'RECEIVING_GROUPS';
export const LOADING_GROUPS = 'LOADING_GROUPS';

export const TOGGLING_RENAME_GROUP = 'TOGGLING_RENAME_GROUP';
export const GROUP_RENAMED = 'GROUP_RENAMED';

export const REMOVING_GROUP = 'REMOVING_GROUP';
export const GROUP_REMOVED = 'GROUP_REMOVED';

export const UPDATING_GROUP = 'UPDATING_GROUP';
export const ADDED_GROUP = 'ADDED_GROUP';

export const UPLOADING_DOCUMENTS = 'UPLOADING_DOCUMENTS';
export const UPLOADING_DOCUMENT_PROGRESS = 'UPLOADING_DOCUMENT_PROGRESS';
export const DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED';
export const UPLOADING_DOCUMENT_FAILED = 'UPLOADING_DOCUMENT_FAILED';
export const MOVING_TO_FILES = 'MOVING_TO_FILES';

export const RECEIVING_DOCUMENTS = 'RECEIVING_DOCUMENTS';
export const REMOVING_DOCUMENT = 'REMOVING_DOCUMENT';
export const REMOVED_FILE = 'REMOVED_FILE';

export const API_READ_FAILED = 'API_READ_FAILED';

