export const GROUPS_RECEIVING = 'GROUPS_RECEIVING';
export const GROUPS_DEFAULTS = 'GROUPS_DEFAULTS';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUP_RENAME_TOGGLE = 'GROUP_RENAME_TOGGLE';
export const GROUP_TOGGLE_UPDATING = 'GROUP_TOGGLE_UPDATING';
export const GROUP_UPDATE_FAILED = 'GROUP_UPDATE_FAILED';
export const GROUP_RENAMED = 'GROUP_RENAMED';
export const GROUP_REMOVED = 'GROUP_REMOVED';
export const GROUP_ADDED = 'GROUP_ADDED';

export const DOCUMENTS_RECEIVING = 'DOCUMENTS_RECEIVING';
export const DOCUMENTS_UPLOADING = 'DOCUMENTS_UPLOADING';
export const DOCUMENT_UPLOAD_IN_PROGRESS = 'DOCUMENT_UPLOAD_IN_PROGRESS';
export const DOCUMENT_UPLOAD_SUCCESS_CLEAN = 'DOCUMENT_UPLOAD_SUCCESS_CLEAN';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED';
export const DOCUMENT_REMOVED = 'DOCUMENT_REMOVED';
export const DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED';

export const API_READ_FAILED = 'API_READ_FAILED';

