// sections
export const FETCH_SECTIONS = 'FETCH_SECTIONS';
export const RECEIVE_SECTIONS = 'RECEIVE_SECTIONS';

export const TOGGLE_SECTION_COLLAPSE = 'TOGGLE_SECTION_COLLAPSE';
export const SWITCH_SECTION_TAB = 'SWITCH_SECTION_TAB';

export const TOGGLE_SECTION_LOADING = 'TOGGLE_SECTION_LOADING';
export const TOGGLE_MANAGE_SECTION_MODAL = 'TOGGLE_MANAGE_SECTION_MODAL';
export const TOGGLE_MANAGE_SECTION_MODAL_LOADING =
    'TOGGLE_MANAGE_SECTION_MODAL_LOADING';

// comments
export const TOGGLE_COMMENT_BOX = 'TOGGLE_COMMENT_BOX';
export const TOGGLE_COMMENT_EDIT = 'TOGGLE_COMMENT_EDIT';
export const TOGGLE_COMMENT_LOADING = 'TOGGLE_COMMENT_LOADING';

export const SUBMITTED_NEW_COMMENT = 'SUBMITTED_NEW_COMMENT';
export const SUBMITTED_EDIT_COMMENT = 'SUBMITTED_EDIT_COMMENT';
export const DELETED_COMMENT = 'DELETED_COMMENT';

// staff
export const RECEIVE_STAFF = 'RECEIVE_STAFF';
export const CHANGE_STAFF_RESPONSE = 'CHANGE_STAFF_RESPONSE';
export const ADDED_STAFF_RESPONSE = 'ADDED_STAFF_RESPONSE';
export const DELETED_STAFF_RESPONSE = 'DELETED_STAFF_RESPONSE';
export const TOGGLE_STAFF_LOADING = 'TOGGLE_STAFF_LOADING';

// questions
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';

// STATUS
export const IN_PROGRESS = 1;
export const APPROVED = 2;
export const DECLINED = 3;
