export const REQUIREMENTS_REQUESTED = 'REQUIREMENTS_REQUESTED';
export const REQUIREMENTS_RECEIVED = 'REQUIREMENTS_RECEIVED';
export const REQUIREMENTS_RELATIONSHIP_UPDATED = 'REQUIREMENTS_RELATIONSHIP_UPDATED';

export const IS_EDITING = 'IS_EDITING';
export const IS_DELETED = 'IS_DELETED';
export const IS_SAVED = 'IS_SAVED';
export const IS_CREATED = 'IS_CREATED';
export const IS_EMPTY_ADDED = 'IS_EMPTY_ADDED';
export const TOGGLE_VIEW_FULL_TEXT = 'TOGGLE_VIEW_FULL_TEXT';

export const UPDATE_TEXT = 'UPDATE_TEXT';
export const UPDATE_MANDATORY_SELECTION = 'UPDATE_MANDATORY_SELECTION';
export const UPDATE_INCLUSIONS_CATEGORY = 'UPDATE_INCLUSIONS_CATEGORY';
export const UPDATE_QUOTE_ID = 'UPDATE_QUOTE_ID';