export const IS_EDITING = 'IS_EDITING';
export const IS_DELETED = 'IS_DELETED';
export const SAVE_REQUIREMENT = 'SAVE_REQUIREMENT';
export const REQUIREMENTS_REQUESTED = 'REQUIREMENTS_REQUESTED';
export const REQUIREMENTS_RECEIVED = 'REQUIREMENTS_RECEIVED';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const IS_SAVED = 'IS_SAVED';
export const IS_DEFAULT_ADDED = 'IS_DEFAULT_ADDED';
export const UPDATE_TEXT = 'UPDATE_TEXT';

export const UPDATE_MANDATORY_SELECTION = 'UPDATE_MANDATORY_SELECTION';
export const UPDATE_INCLUSIONS_SELECTION = 'UPDATE_INCLUSIONS_SELECTION';
export const UPDATE_INCLUSIONS_CATEGORY = 'UPDATE_INCLUSIONS_CATEGORY';
