export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';
export const RECEIVE_SUGGESTIONS_DOCUMENTS = 'RECEIVE_SUGGESTIONS_DOCUMENTS';
export const REMOVE_SUGGESTIONS_DOCUMENT = 'REMOVE_SUGGESTIONS_DOCUMENT';
export const UPDATE_QUOTE_ID = 'UPDATE_QUOTE_ID';

export const UPDATED_CHECKBOX_VALUE = 'UPDATED_CHECKBOX_VALUE';
export const UPDATING_STATUS = 'UPDATING_STATUS';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const ADD_NEW_DOCUMENT = 'ADD_NEW_DOCUMENT';

export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const SELECTED_SUGGESTION = 'SELECTED_SUGGESTION';
export const RESET_SELECTED_SUGGESTION = 'RESET_SELECTED_SUGGESTION';
