export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_CATEGORY_TYPE = 'SELECT_CATEGORY_TYPE';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_SUGGESTIONS = 'REQUEST_SUGGESTIONS';
export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';

export const RESET_INPUTS = 'RESET_INPUTS';