export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_CATEGORY_FILTER = 'SELECT_CATEGORY_FILTER';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';

export const RESET_INPUTS = 'RESET_INPUTS';
export const UPDATE_INPUT = 'UPDATE_INPUT';