export const IS_BUSY = 'IS_BUSY';
export const INITIAL_STATE = 'INITIAL_STATE';
export const AVAILABLE_TAGS_UPDATE  = 'AVAILABLE_TAGS_UPDATE';
export const SELECTED_TAGS_UPDATE  = 'SELECTED_TAGS_UPDATE';
export const SELECTED_TAGS_SAVE = 'SELECTED_TAGS_SAVE';
export const SUPPLIER_ID_UPDATE ='SUPPLIER_ID_UPDATE';
export const REQUEST_FAILED ='REQUEST_FAILED';
