export const IS_BUSY = 'IS_BUSY';
export const ALL_TAGS_UPDATE  = 'ALL_TAGS_UPDATE';
export const REQUEST_FAILED ='REQUEST_FAILED';
export const TAG_COMMENT_UPDATE = 'TAG_COMMENT_UPDATE';
export const SELECTED_TAGS_UPDATE = 'SELECTED_TAGS_UPDATE';
