export const IS_BUSY = 'IS_BUSY';
export const ALL_TAGS_UPDATE  = 'ALL_TAGS_UPDATE';
export const SELECTED_TAGS_UPDATE  = 'SELECTED_TAGS_UPDATE';
export const SELECTED_TAGS_SAVE = 'SELECTED_TAGS_SAVE';
export const SUPPLIER_ID_UPDATE ='SUPPLIER_ID_UPDATE';
export const REQUEST_FAILED ='REQUEST_FAILED';
export const TAG_FOCUS ='TAG_FOCUS';
export const TAG_COMMENT_UPDATE = 'TAG_COMMENT_UPDATE';
